### PR TITLE
feat: basic user ms

### PR DESCRIPTION
**Pull request by DavidLHW**
# Comments

Users microservice serves as the main service to manage users data. At the moment, this microservice is quite large for a single PR so I intend to break it down into multiple PRs (probably 2, this and another).

Refer to the following for what has been completed and what still needs more work.

For more specific information on the implementation and testing, please refer to the readme at users directory.

# Planned functionalities

## Functions

- [x]  get user by id
- [x]  get users by type
- [x]  get buyers by project
- [x]  create user
- [ ]  update user offset
- [ ]  delete user (not priority)

## REST Endpoints

- [x]  GET /users/:id ⇒ get specific user by id (for payment success/failure notification)
- [x]  GET /users
    queries
    - [x]  type = [verifier | seller | buyer] ⇒ get all users by type
    - [x]  project_id <uuid> ⇒ get all users belonging to a project
- [ ]  POST /users/:id/offset ⇒ add user’s offset balance / status
- [ ]  PATCH /users/:id/offset ⇒ update user’s offset balance / status

## db schema

```
_User (1 user - M offset)_
id         uuid
email      text
type text  ("verifier" | "buyer" | "seller")
created_at isotimestamp
updated_at isotimestamp
offset_id  FK

_Buyer(inherits fields from User)_
footprint_in_tCO2e float

_Seller(inherits fields from User)_
project_ids   text[]  // owns which project

Verifier(inherits fields from User)_
milestone_ids text[]  // which milestones to verify
project_ids   text[]  // which project to verify

_Offset (1 user - M offset) (1 milestone - M offset)_
id uuid
milestone_id uuid
user_id FK
amount float32
state varchar (pending | confirmed)
created_at int64
updated_at int64
```

## API Schema

You may test the api by running docker compose and heading to [`http://localhost:8080/swagger/index.html`](http://localhost:8080/swagger/index.html)

### expected api request structure

Create user
```bash
curl --location --request POST 'localhost:8080/api/v1/users' \
--header 'Content-Type: application/json' \
--data-raw '{
  "username": "johndoe",
  "name": "John Doe",
  "email": "johndoe@example.com",
  "type": "verifier",
  "project_id": "asd"
}
'
```

Get User By Id
```bash
curl --location --request GET 'localhost:8080/api/v1/users/7ac24ad8-4e23-4494-b148-f95533520312'
```

Get Users
```bash
curl --location --request GET 'localhost:8080/api/v1/users?type=verifier&project_id=asd'
```

### expected api response structure

```js
{
    "data": object,
    "success": boolean
}
```

### CODE REVIEW

**Review by engzongwei — COMMENTED** [review]
Should the user type be a list of types? e.g. Would there be a case where a user is both a seller and buyer

**Comment by DavidLHW** [comment]
> Should the user type be a list of types? e.g. Would there be a case where a user is both a seller and buyer

We will not support that for now as it doesn't bring much benefit
(user can just log in as a different user type using the same email)

**Review by zhiweit — DISMISSED** [review]

**Comment by nicamanas** [comment]
I have went through and tested with the provided Postman JSONs, also through the Swagger UI. All user endpoints are working as expected. Will we be including more response codes in Swagger documentation, largely for the failure cases?

Also, note that at least for me, Healthcheck endpoint is not working and returning 404 error. 

image

Other endpoints working as expected, do let me know if it works for you and the issue is likely to be on my end.

**Comment by DavidLHW** [comment]
@nicamanas thanks for pointing that out! it was a typo on the swagger, the healthcheck endpoint should be `/api/v1/health` instead of `/api/v1/healthcheck`, I'll update it

**Review by nicamanas — APPROVED** [review]

**Pull request merged**
